### ISSUE TITLE
Implement "debug" mode

### ISSUE THREAD

**Issue by WolfenCLI** [furSUDO/SUDOku#2]
Possible idea to add a variable (or maybe `os.env.DEBUG || true/false`) to wrap all the console logs in if statements. Reason being printing to console is expensive (well, more than an if at least).  

Example of debugging log that could be avoided:  
https://github.com/furSUDO/SUDOku/blob/c0e79cd3958ba20e8ea574c8568d0145fa68b199/index.js#L136

**Comment by furSUDO** [comment]
added debug mode
